"""Console script for telemetry."""
import sys
import click
import datetime
import telemetry


@click.group()
def cli():
    pass


@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.option(
    "--filename",
    default="resource_utilization.csv",
    help="Full path to resource utilization csv file generated by HDL builds",
)
def log_hdl_resources_from_csv(server, filename):
    tel = telemetry.ingest(server=server)
    tel.log_hdl_resources_from_csv(filename)


@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.argument("in_args", nargs=-1)
def log_boot_logs(server, in_args):
    entry = {
        "boot_folder_name": "NA",
        "hdl_hash": "NA",
        "linux_hash": "NA",
        "boot_partition_hash": "NA",
        "hdl_branch": "NA",
        "linux_branch": "NA",
        "boot_partition_branch": "NA",
        "is_hdl_release": False,
        "is_linux_release": False,
        "is_boot_partition_release" : False,
        "uboot_reached": False,
        "linux_prompt_reached": False,
        "drivers_enumerated": 0,
        "dmesg_warnings_found": 0,
        "dmesg_errors_found": 0,
        "jenkins_job_date": datetime.datetime.now(),
        "jenkins_build_number": 0,
        "jenkins_project_name": 0,
        "jenkins_agent": "NA",
    }
    if len(in_args) == 0:
        click.echo("Must have non-zero arguments for database entry")
        sys.exit(1)
    if int(len(in_args) / 2) != len(in_args) / 2:
        click.echo(
            "ERROR: Number of inputs arguments must be even\n"
            + "       and in the form of: entry1<space>value1<space>entry2<space>value2"
        )
        sys.exit(1)
    for i in range(0, len(in_args), 2):
        if in_args[i] in entry:
            if in_args[i + 1].lower() == "true":
                entry[in_args[i]] = True
            elif in_args[i + 1].lower() == "false":
                entry[in_args[i]] = False
            else:
                entry[in_args[i]] = in_args[i + 1]
        else:
            click.echo("ERROR: " + in_args[i] + " not a valid entry")
            sys.exit(1)
    tel = telemetry.ingest(server=server)
    tel.log_boot_tests(**entry)


@click.command()
def main(args=None):
    """Console script for telemetry."""
    click.echo("Replace this message by putting your code into " "telemetry.cli.main")
    click.echo("See click documentation at https://click.palletsprojects.com/")
    return 0


cli.add_command(log_boot_logs)
cli.add_command(log_hdl_resources_from_csv)
cli.add_command(main)

if __name__ == "__main__":
    sys.exit(cli())  # pragma: no cover
