"""Console script for telemetry."""
import sys
import click
import datetime
import telemetry
import os


def validate(field, value, schema):
    """Validate a field and value data type
    againts a given es schema
    """
    properties = schema["mappings"]["properties"]
    type_maps = {
        "keyword" : "str",
        "text" : "str",
        "boolean" : "bool",
        "integer" : "int",
        "date" : "datetime"
    }
    if not field in properties.keys():
        raise Exception(f"Schema validator: {field} not supported")

    # Validate data type
    expected_type = type_maps[properties[field]["type"]]
    actual_type = type(value).__name__

    try:
        if not actual_type == expected_type:
            raise Exception(f"Schema validator: {field} expects {expected_type} type, {actual_type} is given")
    except Exception:
        if expected_type == "bool":
            if value.lower() in ["false", "true"]:
                value = bool(value)
        if expected_type == "int":
            value = int(value)

@click.group()
def cli():
    pass


@click.command()
@click.option(
    "--tdir",
    default="/test/logs/unprocessed",
    help="Path to directory of unprocessed test logs",
)
@click.option("--server", default=None, help="Address of mongo server")
@click.option("--username", default=None, help="Username for mongo server")
@click.option("--password", default=None, help="Password for mongo server")
@click.option("--dbname", default=None, help="Target collection for mongo server")
@click.option("--board", default=None, help="Name of target board")
def prod_logs_upload(tdir, server, username, password, dbname, board):
    """Upload unprocessed test logs to mongo for synchrona."""
    sync = telemetry.prod.BoardLog(server, username, password, dbname, board)
    sync.default_unprocessed_log_dir = tdir
    sync.default_processed_log_dir = os.path.join(tdir, "processed")
    if not os.path.isdir(sync.default_processed_log_dir):
        os.mkdir(sync.default_processed_log_dir)
    sync() # go go


@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.option(
    "--filename",
    default="resource_utilization.csv",
    help="Full path to resource utilization csv file generated by HDL builds",
)
def log_hdl_resources_from_csv(server, filename):
    tel = telemetry.ingest(server=server)
    tel.log_hdl_resources_from_csv(filename)


@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.argument("in_args", nargs=-1)
def log_artifacts(server, in_args):
    entry = {
        "url": "NA",
        "server": "NA",
        "job": "NA",
        "job_no": 0,
        "job_date": None,
        "job_build_parameters": "NA",
        "file_name": "NA",
        "target_board": "NA",
        "artifact_info_type": "NA",
        "payload_raw": "NA",
        "payload_ts": "NA",
        "payload": "NA",
        "payload_param": "NA"
    }
    if len(in_args) == 0:
        click.echo("Must have non-zero arguments for database entry")
        sys.exit(1)
    if int(len(in_args) / 2) != len(in_args) / 2:
        click.echo(
            "ERROR: Number of inputs arguments must be even\n"
            + "       and in the form of: entry1<space>value1<space>entry2<space>value2"
        )
        sys.exit(1)
    for i in range(0, len(in_args), 2):
        if in_args[i] in entry:
            if in_args[i + 1].lower() == "true":
                entry[in_args[i]] = True
            elif in_args[i + 1].lower() == "false":
                entry[in_args[i]] = False
            else:
                entry[in_args[i]] = in_args[i + 1]
        else:
            click.echo("ERROR: " + in_args[i] + " not a valid entry")
            sys.exit(1)
    tel = telemetry.ingest(server=server)
    tel.log_artifacts(**entry)

@click.command()
@click.option("--jenkins-server", required=True, help="Address of Jenkins server")
@click.option("--jenkins-username", required=False, help="Username with access on the Jenkins server")
@click.option("--jenkins-password", required=False, help="Password for Jenkins username")
@click.option("--es-server", required=True, help="Address of Elasticsearch server")
@click.option("--job-name", default="HW_tests/HW_test_multiconfig", help="Name of Jenkins job")
@click.option("--job", multiple=True, help="Job(s)/build(s) to process")
def grab_and_log_artifacts(
        jenkins_server,
        jenkins_username,
        jenkins_password,
        es_server,
        job_name,
        job
    ):
    if not len(job) > 0:
        click.echo("Atleast 1 Job/Build (--job) is needed.")
        sys.exit(1)
    g = telemetry.gargantua(
        jenkins_server,
        jenkins_username,
        jenkins_password,
        es_server,
        job_name,
        job
    )
    g.log_artifacts()

@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.argument("in_args", nargs=-1)
def log_boot_logs(server, in_args):
    
    tel = telemetry.ingest(server=server)
    schema = tel.db.import_schema(tel._get_schema("boot_tests.json"))
    entry = dict()
    for k,v in schema["mappings"]["properties"].items():
        if k == "source_adjacency_matrix":
            continue
        if v["type"] in ["txt","keyword"]:
            entry.update({k:"NA"})
        elif v["type"] in ["integer"]:
            entry.update({k: 0})
        elif v["type"] in ["boolean"]:
            entry.update({k: False})
        elif k == "jenkins_job_date":
            entry.update({k:datetime.datetime.now()})
        else:
            entry.update({k: None})

    if len(in_args) == 0:
        click.echo("Must have non-zero arguments for database entry")
        sys.exit(1)
    if int(len(in_args) / 2) != len(in_args) / 2:
        click.echo(
            "ERROR: Number of inputs arguments must be even\n"
            + "       and in the form of: entry1<space>value1<space>entry2<space>value2"
        )
        sys.exit(1)

    for i in range(0, len(in_args), 2):
        if in_args[i] in entry:
            validate(in_args[i], in_args[i+1],schema)
            if in_args[i + 1].lower() == "true":
                entry[in_args[i]] = True
            elif in_args[i + 1].lower() == "false":
                entry[in_args[i]] = False
            else:
                entry[in_args[i]] = in_args[i + 1]
        else:
            click.echo("ERROR: " + in_args[i] + " not a valid entry")
            sys.exit(1)

    tel = telemetry.ingest(server=server)
    tel.log_boot_tests(**entry)

@click.command()
@click.option("--server", default="picard", help="Address of Elasticsearch server")
@click.argument("in_args", nargs=-1)
def log_noos_logs(server, in_args):
    
    tel = telemetry.ingest(server=server)
    schema = tel.db.import_schema(tel._get_schema("noos_tests.json"))
    entry = dict()
    for k,v in schema["mappings"]["properties"].items():
        if v["type"] in ["text","keyword"]:
            entry.update({k:"NA"})
        elif v["type"] in ["integer"]:
            entry.update({k: 0})
        elif v["type"] in ["boolean"]:
            entry.update({k: False})
        elif k == "jenkins_job_date":
            entry.update({k:datetime.datetime.now()})
        else:
            entry.update({k: None})

    if len(in_args) == 0:
        click.echo("Must have non-zero arguments for database entry")
        sys.exit(1)
    if int(len(in_args) / 2) != len(in_args) / 2:
        click.echo(
            "ERROR: Number of inputs arguments must be even\n"
            + "       and in the form of: entry1<space>value1<space>entry2<space>value2"
        )
        sys.exit(1)

    for i in range(0, len(in_args), 2):
        if in_args[i] in entry:
            validate(in_args[i], in_args[i+1],schema)
            if in_args[i + 1].lower() == "true":
                entry[in_args[i]] = True
            elif in_args[i + 1].lower() == "false":
                entry[in_args[i]] = False
            else:
                entry[in_args[i]] = in_args[i + 1]
        else:
            click.echo("ERROR: " + in_args[i] + " not a valid entry")
            sys.exit(1)

    tel = telemetry.ingest(server=server)
    tel.log_noos_tests(**entry)

@click.command()
def main(args=None):
    """Console script for telemetry."""
    click.echo("Replace this message by putting your code into " "telemetry.cli.main")
    click.echo("See click documentation at https://click.palletsprojects.com/")
    return 0


cli.add_command(prod_logs_upload)
cli.add_command(log_boot_logs)
cli.add_command(log_noos_logs)
cli.add_command(log_hdl_resources_from_csv)
cli.add_command(log_artifacts)
cli.add_command(grab_and_log_artifacts)
cli.add_command(main)

if __name__ == "__main__":
    sys.exit(cli())  # pragma: no cover
